[package]
name = "rebootinto-tui"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"

[dependencies.rebootinto-core]
path = "../core"

[dependencies.tui]
git = "https://github.com/fdehau/tui-rs.git"
rev = "e183d63a5ef4680d68def76fff06156c4e67e87e"
default-features = false
optional = true

[dependencies.termion]
version = "1.5"
optional = true

[dependencies.crossterm]
version = "0.10"
optional = true

[features]
crossterm_backend = ["crossterm", "tui", "tui/crossterm"]
crossterm_backend_sync_input = ["crossterm_backend"]
termion_backend = ["termion", "tui", "tui/termion"]
default = ["crossterm_backend"]

[build-dependencies]
embed-resource = "1.2.0"
