[package]
name = "rebootinto-tui"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"

[dependencies.rebootinto-core]
path = "../core"

[dependencies.tui]
git = "https://github.com/TimonPost/tui-rs.git"
rev = "9a6676462ad5356f66a58d13cfe9cf57c6479cd1"
default-features = false
optional = true

[dependencies.termion]
version = "1.5"
optional = true

[dependencies.crossterm]
version = "0.9"
optional = true

[features]
crossterm_backend = ["crossterm", "tui", "tui/crossterm"]
termion_backend = ["termion", "tui", "tui/termion"]
# default = ["termion_backend"]
default = ["crossterm_backend"]
