[package]
name = "rebootinto-tui"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
tui = "0.5"
termion = "1.5"
rand = "0.6"
failure = "0.1"
failure_derive = "0.1"

[dependencies.rebootinto-core]
path = "../core"
