language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

dist: xenial
addons:
  apt:
    packages:
      - libgtk-3-dev
      - python3
      - python3-pip
      - python3-setuptools
      - ninja-build

install:
  - pip3 install --user meson
  - cargo install cargo-deb

script:
  - cargo build --release
  - cargo test --verbose --release
  - BUILD_PATHS="cli tui iui" scripts/build-debs
