[package]
name = "rebootinto-cli"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
failure = "0.1"
clap = "2.33"

[dependencies.rebootinto-core]
path = "../core"

[build-dependencies]
embed-resource = "1.2.0"
