[package]
name = "rebootinto-core"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"
description = "The core API for rebooting into other OS."
license = "MIT"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
simplereboot = "0.1"
efivar = "0.1"
efibootnext = "0.1"
