[package]
name = "rebootinto-core"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"

[dependencies.efibootnext]
git = "https://github.com/MOZGIII/efibootnext.git"
rev = "380b99ea4ab5b405c5c2bcae9c3b2262375eb605"

[dependencies.efivar]
git = "https://github.com/MOZGIII/efiboot-rs.git"
rev = "551798e5486597879ffa7aff0e42712cf66c0012"
