[package]
name = "rebootinto-iui"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
failure = "0.1"

[dependencies.iui]
git = "https://github.com/MOZGIII/libui-rs.git"
rev = "aa89ecef90ed1cb462ebbd1e159fd6e4f383b306"
features = ["static"]

[dependencies.rebootinto-core]
path = "../core"

[build-dependencies]
embed-resource = "1.2.0"
