name: "Build GTK"
description: "Build GTK from source on Windows using msvc toolchain"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache
      with:
        path: c:/gnome
        key: ${{ runner.os }}-gtk
        restore-keys: |
          ${{ runner.os }}-gtk

    - name: Set up the PATH environment
      shell: bash
      run: |
        echo "C:\pkg-config-lite-0.28-1\bin" >>"$GITHUB_PATH"
        echo "C:\gnome\bin" >>"$GITHUB_PATH"
        echo "PKG_CONFIG_PATH=C:\gnome\lib\pkgconfig" >>"$GITHUB_ENV"

    - name: Install pkgconfig-lite
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://deac-fra.dl.sourceforge.net/project/pkgconfiglite/0.28-1/pkg-config-lite-0.28-1_bin-win32.zip -OutFile /pkg_config_lite.zip -MaximumRetryCount 5
        Expand-Archive /pkg_config_lite.zip -DestinationPath C:\
        ls C:\
        ls C:\pkg-config-lite-0.28-1
        ls C:\pkg-config-lite-0.28-1\bin
        pkg-config --version

    - name: Clone GTK
      shell: pwsh
      working-directory: /
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        git clone https://gitlab.gnome.org/GNOME/gtk.git --depth 1

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      shell: pwsh
      run: pip install meson ninja

    - name: Prepare GTK build
      shell: pwsh
      working-directory: /gtk
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        meson setup builddir `
          --prefix="C:/gnome" `
          --backend=ninja `
          -Dbackend_max_links=1 `
          -Dbuild-demos=false `
          -Dbuild-tests=false `
          -Dmedia-gstreamer=disabled `
          -Dbuild-examples=false `
          -Dglib:tests=false `
          -Dharfbuzz:tests=disabled `
          -Dharfbuzz:docs=disabled `
          -Dgraphene:tests=false `
          -Dgdk-pixbuf:tests=false `
          -Dcairo:tests=disabled

    - name: Build and install GTK
      shell: pwsh
      working-directory: /gtk
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        meson install -C builddir

    - name: List the contents
      shell: bash
      run: |
        ls -laR "C:/gnome"
